---
- name: Module Load for containerd
  copy:
    content: |
      overlay
      br_netfilter
      ip_conntrack
    dest: /etc/modules-load.d/containerd.conf

- name: modprobe
  modprobe:
    name: "{{item}}"
    state: present
  loop:
    - ip_conntrack
    - br_netfilter
    - overlay

- name: sysctl for k8s-cri
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.netfilter.nf_conntrack_max = 262144
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  notify:
    - sysctl--system

- name: Add repositories key docker
  apt_key:
    url: 'https://download.docker.com/linux/debian/gpg'
    state: present

- name: Add repositories docker
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable'
    state: present
    filename: 'docker'

# tasks file for containerd
- name: Add repositories key gvisor
  apt_key:
    url: 'https://gvisor.dev/archive.key'
    state: present

- name: Add repositories gvisor
  apt_repository:
    repo: 'deb [arch=amd64,arm64] https://storage.googleapis.com/gvisor/releases release main'
    state: present
    filename: 'gvisor'

- name: Add repositories key k8s
  apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    state: present

- name: Add repositories k8s
  apt_repository:
    repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: 'k8s'

- name: containerd-  Update the repository cache and install containerd
  ansible.builtin.apt:
    state: latest
    update_cache: yes
    allow_change_held_packages: true
    pkg:
      - containerd.io=1.6.21-1

- name: containerd - Creates directory
  file:
    path: /etc/containerd/certs.d/docker.io/
    state: directory
    recurse: yes

- name: repo local
  template:
    src: repo.toml
    dest: '/etc/containerd/certs.d/docker.io/hosts.toml'
  when: global_repo is defined
  notify:
    - Restart-service-containerd

- name: gVisor - Install sunsc
  ansible.builtin.apt:
    update_cache: yes
    allow_change_held_packages: true
    pkg:
      - runsc

- name: gVisor - config
  copy:
    src: config.toml
    dest: '/etc/containerd/config.toml'
  notify:
    - Restart-service-containerd

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/meta_module.html#meta-module

- name: Install crictl Software
  apt:
    pkg:
      - cri-tools

- name: crictl - crictl.yaml
  copy:
    src: crictl.yaml
    dest: '/etc/crictl.yaml'
