- name: "Creates directory"
  file:
    path: "{{CERT_PATH}}"
    state: directory
    recurse: yes


- name: "CA Kubernetes certificate "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['ca_kubernetes']['crt']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['ca_kubernetes']['crt']['content']|b64decode }}"

- name: "CA Typha certificate "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['ca_typha']['crt']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['ca_typha']['crt']['content']|b64decode }}"


- name: "system_kube_proxy certificate "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['system_kube_proxy']['crt']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['system_kube_proxy']['crt']['content']|b64decode }}"

- name: "system_kube_proxy key "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['system_kube_proxy']['key']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['system_kube_proxy']['key']['content']|b64decode }}"


- name: "system_kube_proxy certificate "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['system_kube_proxy']['crt']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['system_kube_proxy']['crt']['content']|b64decode }}"


- name: "calico_cni key "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['calico_cni']['key']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['calico_cni']['key']['content']|b64decode }}"

- name: "calico_cni certificate "
  copy:
    dest: "{{ hostvars['INIT_CA_HOST']['calico_cni']['crt']['source'] }}"
    content: "{{ hostvars['INIT_CA_HOST']['calico_cni']['crt']['content']|b64decode }}"