- name: Create private key for new certificate on {{hostname}} {{inventory_hostname}}
  community.crypto.openssl_privatekey:
    path: /etc/ssl/private/certificate.key

- name: system:node:{{hostname}}
  include_tasks:
    file: sign.yml
  vars: 
    _path_key: "/etc/ssl/private/certificate.key"
    _path_crt: /etc/ssl/certs/certificate.pem
    _common_name: "system:node:{{hostname}}"
    _organization_name: "system:nodes"
    _subject_alt_name:
      - "DNS:{{hostname}}.{{domain}}"
      - "DNS:{{hostname}}"
      - "IP:{{inventory_hostname}}"
    _ca_key: "{{ hostvars['INIT_CA_HOST']['ca_kubernetes']['key']['source'] }}"
    _ca_pem: "{{ hostvars['INIT_CA_HOST']['ca_kubernetes']['crt']['source'] }}"
