- name: kubectl config {{_name}}
  ansible.builtin.command: "kubectl config {{item}} --kubeconfig=/etc/kubernetes/config/{{_crt}}.kubeconfig"
  loop:
    - "set-cluster k8s --certificate-authority=/etc/kubernetes/pki/Kubernetes_CA.pem --embed-certs=true --server=https://{{KUBERNETES_PUBLIC_ADDRESS}}:6443"
    - "set-credentials {{_name}} --client-certificate=/etc/kubernetes/pki/{{_crt}}.pem --client-key=/etc/kubernetes/pki/{{_crt}}.key --embed-certs=true"
    - "set-context default --cluster=k8s --user={{_name}}"
    - "use-context default"