- name: kubectl config {{_name}}
  ansible.builtin.command: "kubectl config {{item}} --kubeconfig=/etc/kubernetes/config/{{_crt}}.kubeconfig"
  loop:
    - "set-cluster {{ cluster_name }} --certificate-authority={{CERT_PATH}}/ca_kubernetes.pem --embed-certs=true --server=https://{{KUBERNETES_PUBLIC_ADDRESS}}:6443"
    - "set-credentials {{_name}} --client-certificate={{CERT_PATH}}/{{_crt}}.pem --client-key={{CERT_PATH}}/{{_crt}}.key --embed-certs=true"
    - "set-context default --cluster={{ cluster_name }} --user={{_name}}"
    - "use-context default"