- name: "[{{hostname}}] {{_NAME}} "
  ansible.builtin.shell: "{{_CMD}}"
  register: etcd_output

- name: "[{{hostname}}] {{_NAME}} debug "
  debug:
    msg: 
    - "{{_CMD}}"
    - "{{etcd_output.stdout_lines}}"
