# kubectl create namespace argocd
# kubectl apply -n argocd -f
#  ~/Downloads/argocd-linux-amd64 admin initial-password -n argocd
# argocd app create test_argocd --repo git@github.com:goryszewski/test_argocd.git --path test_argocd --dest-namespace default

- name: kubectl create namespace argocd
  ansible.builtin.command: kubectl create namespace argocd

  ignore_errors: true
  run_once: true

- name: Copy argocd.yml
  ansible.builtin.copy:
    src: argocd.yml
    dest: /etc/kubernetes/config/argocd.yml
  register: touch_argocd_yml

- name: kubectl apply argocd.yml
  ansible.builtin.command: kubectl apply -n argocd  -f /etc/kubernetes/config/argocd.yml
  when: touch_argocd_yml.changed
  ignore_errors: true
  run_once: true

- name: Copy argo_app.yml
  ansible.builtin.copy:
    src: argo_app.yml
    dest: /etc/kubernetes/config/argo_app.yml
  register: touch_argo_app_yml

- name: kubectl apply argo_app.yml
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/argo_app.yml
  when: touch_argo_app_yml.changed
  ignore_errors: true
  run_once: true