- import_tasks: 00_calico_dns.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- import_tasks: 01_helm.yml


- import_tasks: 02_ingress.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- import_tasks: 03_argocd.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true
