- import_tasks: 00_calico_dns.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- import_tasks: 01_helm.yml


- import_tasks: 02_ingress.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- import_tasks: 03_argocd.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- import_tasks: 04_deploy_app.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- name: "[localhost] kubectl local"
  delegate_to: 'localhost'
  run_once: true
  ansible.builtin.command: scp root@master01.{{domain}}:/root/.kube/config ~/.kube/config

- name: "[localhost] kubectl test"
  delegate_to: 'localhost'
  run_once: true
  ansible.builtin.command: kubectl get nodes -o wide
  register: output_test

- name: "[localhost] etcdctl debug "
  debug:
    msg: output_test