- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"

- name: Install Default Software
  ansible.builtin.apt:
    pkg:
      - resolvconf
  
- name: Template a file to head.j2
  ansible.builtin.template:
    src: head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  register: touch_tail

- name: resolvconf  -u
  ansible.builtin.command: resolvconf  -u
  when: 
    - touch_tail.changed

- name: Install Default Software
  ansible.builtin.apt:
    pkg:
      - tcpdump
      - gpg
      - python3-pip
      - net-tools
      - socat 
      - conntrack 
      - ipset
      - curl
      - sudo
    state: latest
    update_cache: yes

- name: Install apt by OS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ common.pkg }}"
  when: common.pkg is defined

- name: Install pip by OS
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ common.pip }}"
  when: common.pip is defined
