- name: Download file kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/
    mode: 'u=rwx,g=rx,o=rx'
    checksum: sha256:https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kubectl.sha256

- name: Creates directory
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - /root/.kube/

- name: "KubeConfig Admin"
  include_tasks:
    file: ./_share/_.kubeconfig.yml
  vars:
    _name: "{{element._name}}"
    _crt: "{{element._crt}}"
    _IP: "{{KUBERNETES_PUBLIC_ADDRESS}}"
    _path: "/root/.kube/config"
  loop:
    - {_name: 'admin',_crt: "admin"}
  loop_control:
    loop_var: element

- name: "[Cluster] - Wait for kube-apiserver Pod is UP"
  ansible.builtin.uri:
    url: "https://{{ inventory_hostname }}:6443/version"
    return_content: true
    validate_certs: false
  register: register_result_kube_apiserver
  until: register_result_kube_apiserver.status == 200
  retries: 20
  delay: 5

- import_tasks: 02_k8s.yml
- import_tasks: 03_calico.yml


- name: Get local kubeconfig
  fetch:
    src: /root/.kube/config
    dest: ~/.kube
    flat: True
  delegate_to: '{{groups.init[0]}}'
  ignore_errors: true
  run_once: true
