---
- name: Copy /etc/kubernetes/config/ingres.yml
  ansible.builtin.copy:
    src: ingres.yml
    dest: /etc/kubernetes/config/ingres.yml
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: touch_ingres_yml

- name: helm install ingress
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/ingres.yml
  when: touch_ingres_yml.changed
