
- name: Download files crds.yaml
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v{{calico_version}}/manifests/crds.yaml
    dest: /etc/kubernetes/config/
  register: touch_crds

- name: kubectl apply crds.yaml
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/crds.yaml
  ignore_errors: true
  run_once: true

- name: "[Cluster] - Wait for crds ippools.crd.projectcalico.org"
  ansible.builtin.command: kubectl get customresourceDefinition ippools.crd.projectcalico.org
  register: register_result_crds
  until: register_result_crds.rc == 0
  retries: 20
  delay: 5

# file
- name: kubectl create --form-file
  ansible.builtin.command: "{{ item }}"
  ignore_errors: true
  run_once: true
  loop:
    - kubectl create secret generic -n kube-system calico-typha-certs --from-file=/etc/kubernetes/pki/typha.key       --from-file=/etc/kubernetes/pki/typha.pem
    - kubectl create secret generic -n kube-system calico-node-certs  --from-file=/etc/kubernetes/pki/calico-node.key --from-file=/etc/kubernetes/pki/calico-node.pem
    - kubectl create configmap      -n kube-system calico-typha-ca    --from-file=/etc/kubernetes/pki/ca_typha.pem

# end FILE


# BEGIN RBAC

- name: Copy a file to calico01_RBAC.yml
  ansible.builtin.copy:
    src: calico01_RBAC.yml
    dest: /etc/kubernetes/config/calico01_RBAC.yml
  register: touch_calico01_RBAC

- name: kubectl apply calico01_RBAC
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/calico01_RBAC.yml
  ignore_errors: true
  run_once: true

# END RBAC
