- name: "[HAPROXY] Install"
  ansible.builtin.package:
    name: haproxy
    state: present

- name: "[HAPROXY] configuration file"
  template:
    src: "config.j2"
    dest: "/etc/haproxy/haproxy.cfg"

  notify:
    - Restart Haproxy