
- name: BIND - Install
  ansible.builtin.apt:
    update_cache: yes
    allow_change_held_packages: true
    pkg:
      - bind9 
      - bind9utils 
      - bind9-doc

- name: Creates directory /var/lib/bind/zones
  file:
    path: "{{item}}"
    state: directory
    owner: bind
    group: bind
    mode: '0644'
  loop:
    - /var/lib/bind/zones

- name: Template a file to dns.db.j2
  ansible.builtin.template:
    src: dns.db.j2
    dest: /var/lib/bind/{{domain}}.zone
    owner: bind
    group: bind
    mode: '0644'

  notify:
    - Restart bind9

- name: Copy a file to named.conf.options
  ansible.builtin.copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: '0644'
  notify:
    - Restart bind9

- name: Copy a file to named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: '0644'
  notify:
    - Restart bind9