- name: Download files
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: /opt/
    mode: 'u=rwx,g=rx,o=rx'
    checksum: sha256:ecc41b3b4d53f7b9c16a370419a25a133e48c09dfc49499d63bcc0c5e0cf3d01

- name: unarchive prometheus
  ansible.builtin.unarchive:
    src: /opt/node_exporter-1.6.1.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes

- name: Template a file to node_explorer
  ansible.builtin.copy:
    src: node_explorer.service
    dest: /etc/systemd/system/node_explorer.service
  register: touch_node_explorer_service

- name: Enable service node_explorer
  ansible.builtin.systemd:
    name: node_explorer
    enabled: true
    daemon_reload: true
    state: restarted
  when: touch_node_explorer_service.changed