- name: Download files
  ansible.builtin.get_url:
    url: "{{item}}"
    dest: /usr/local/bin/
    mode: 'u=rwx,g=rx,o=rx'
  loop:
    - "https://storage.googleapis.com/kubernetes-release/release/v{{k8s_version}}/bin/linux/amd64/kubectl"
    - "https://storage.googleapis.com/kubernetes-release/release/v{{k8s_version}}/bin/linux/amd64/kubelet"

- name: Creates directory /etc/kubernetes/manifest
  file:
    path: "{{item}}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: '0700'
  loop:
    - "/etc/kubernetes/manifest"
    - "/etc/kubernetes/config"
    

- name: kubectl config step 1
  ansible.builtin.command: kubectl config set-cluster kubernetes-the-hard-way --certificate-authority=/etc/kubernetes/pki/ca_kubernetes.pem --embed-certs=true --server=https://{{KUBERNETES_PUBLIC_ADDRESS}}:6443 --kubeconfig=/etc/kubernetes/config/{{hostname}}.kubeconfig
- name: kubectl config step 2
  ansible.builtin.command: kubectl config set-credentials system:node:{{hostname}} --client-certificate=/etc/ssl/certs/certificate.pem --client-key=/etc/ssl/private/certificate.key --embed-certs=true --kubeconfig=/etc/kubernetes/config/{{hostname}}.kubeconfig
- name: kubectl config step 3
  ansible.builtin.command: kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:node:{{hostname}} --kubeconfig=/etc/kubernetes/config/{{hostname}}.kubeconfig
- name: kubectl config step 4
  ansible.builtin.command: kubectl config use-context default --kubeconfig=/etc/kubernetes/config/{{hostname}}.kubeconfig

- name: Creates directory /var/lib/kubelet/
  file:
    path: /var/lib/kubelet/
    state: directory
    owner: root
    group: root
    mode: '0700'





- name: Template a file to kubelet-config.yaml
  ansible.builtin.template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml
  register: touch_kubelet1_service

- name: Template a file to kubelet.service.j2
  ansible.builtin.template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  register: touch_kubelet2_service

- name: Enable service kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    daemon_reload: true
    state: restarted
