---

- name: "CA Kubernetes"
  include_tasks:
    file: _ca.yml
  vars: 
    _name_file: 'ca_kubernetes'
    _CA_name: "Kubernetes CA "

- name: "CA ETCD"
  include_tasks:
    file: _ca.yml
  vars: 
    _name_file: 'ca_etcd'
    _CA_name: "ETCD CA "

- name: "CA Typha"
  include_tasks:
    file: _ca.yml
  vars: 
    _name_file: 'ca_typha'
    _CA_name: "Calico Typha CA"