- name: "Add dumy CA host"
  add_host:
    name:   "INIT_CA_HOST"
    data:  []

- name: "Creates directory"
  file:
    path: "{{path_ca}}"
    state: directory
    recurse: yes

- name: Run singleton
  block:
  - import_tasks: 00_generate_CA.yml
  - import_tasks: 01_generate_certs.yml
  delegate_to: '{{groups.init[0]}}'
  run_once: true

- import_tasks: 02_redistributed_CA_certs.yml

# - name: test debug
#   debug:
#     msg: "{{item.key}}"
#   loop: "{{hostvars['INIT_CA_HOST'] | dict2items}}"
#   when: '"share_" in item["key"]'
