---
# tasks file for vault

- name: Add repositories key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present


- name: Add repositories
  apt_repository:
    repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main'
    state: present
    filename: 'hashicorp.list'


- name: vault - Install
  ansible.builtin.apt:
    update_cache: yes
    allow_change_held_packages: true
    pkg:
      - vault
