- hosts: syslog
  gather_facts: yes
  roles:
    - rsyslog
  tags: [ LOG ]

- hosts: haproxy
  gather_facts: no
  roles:
    - haproxy
    - keepalive
    - bind
    - bird
  tags: [ LB, HA, BGP, DNS ]

- hosts: all
  gather_facts: yes
  roles:
    - firewall
    - common
    - node_explorer
  tags: [ ]

- hosts: exabgp
  gather_facts: no
  roles:
    - exabgp
  tags: [ EXABGP ]

- hosts: controlplane
  gather_facts: no
  roles:
    - ca
  tags: [ CA ]

# - hosts: monit
#   gather_facts: no
#   roles:
#     - crt
#     - prometheus
#     - grafana
#     - nginx
#   tags: [ PROMETHEUS ]

- hosts: nodeK8S
  gather_facts: no
  roles:
    - crt
    - containerd
    - kubelet
    - kube-proxy
    - calico
  tags: [ ETCD ]

- hosts: etcd
  gather_facts: no
  roles:
    # - etcd
    - etcd_pod
  tags: [ ETCD ]

# - hosts: controlplane
#   gather_facts: no
#   roles:
#     - crt
#     - containerd
#     - kubelet
#     - kube-proxy
#     - calico
#     - kube-apiserver_pod
#     - kube-scheduler_pod
#     - kube-controller-manager_pod
#     - cloud-controller-manager
#   tags: [ CP ]

# - hosts: worker
#   gather_facts: no
#   roles:
#     - crt
#     - containerd
#     - kubelet
#     - kube-proxy
#     - calico
#   tags: [ WORKER ]

# - hosts: controlplane
#   gather_facts: no
#   roles:
#     - cluster_init
#   tags: [ INIT ]

# - hosts: controlplane
#   gather_facts: no
#   roles:
#     - cluster_post
#   tags: [ POST ]
