- hosts: haproxy
  gather_facts: no
  roles:
    - haproxy
    - keepalive
    - dns
    - common
    # - bgp
  tags: [ LB, HA, BGP, DNS ]

- hosts: controlplane
  gather_facts: no
  roles:
    - common
    - ca
  tags: [ CA ]

- hosts: worker
  gather_facts: no
  roles:
    - common
    - certs
  tags: [ CRT ]

- hosts: etcd
  gather_facts: no
  roles:
    - etcd
  tags: [ ETCD ]

- hosts: controlplane
  gather_facts: no
  roles:
    - controlplane
  tags: [ CP ]

- hosts: controlplane
  gather_facts: no
  roles:
    - cluster_pre
  tags: [ PRE ]

- hosts: worker
  gather_facts: no
  roles:
    - worker_v2
  tags: [ WORKER ]

- hosts: controlplane
  gather_facts: no
  roles:
    - cluster_post
  tags: [ POST ]
