- name: Download file kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/
    mode: 'u=rwx,g=rx,o=rx'
    checksum: sha256:https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kubectl.sha256

- name: Creates directory 
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - /root/.kube/

- name: Template a file to kube-controller-manager.kubeconfig
  ansible.builtin.template:
    src: kubeconfig.j2
    dest:  /root/.kube/config

- import_tasks: 02_k8s.yml
- import_tasks: 03_calico.yml
