services:
  registry:
    image: registry
    volumes:
      - /srv/store:/registry
    ports:
      - 5000:5000
    environment:
      - SETTINGS_FLAVOR=local
      - STORAGE_PATH=/registry

  mirror:
    image: registry
    ports:
      - 5555:5000
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - /srv/cache:/registry

  squid:
    build:
      dockerfile: ./Dockerfile-squid
    ports:
      - 3128:3128
    volumes:
      - ./files/squid.conf:/etc/squid/squid.conf
      - ./files/ca.pem:/etc/squid/ca.pem
      - /srv/squid:/srv/squid
