services:
  registry:
    restart: always
    image: registry
    volumes:
      - ./files/registry_config.yml:/etc/docker/registry/config.yml
      - /srv/store:/var/lib/registry
    ports:
      - 5000:5000

  mirror:
    restart: always
    image: registry
    ports:
      - 5555:5000
    volumes:
      - ./files/config.yml:/etc/docker/registry/config.yml
      - /srv/cache:/registry

  squid:
    restart: always
    build:
      dockerfile: ./Dockerfile-squid
    ports:
      - 3128:3128
    volumes:
      - ./files/squid.conf:/etc/squid/squid.conf
      - ./files/ca.pem:/etc/squid/ca.pem
      - /srv/squid:/srv/squid
